[package]
name = "reth-node-telos"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
# reth
reth-chainspec.workspace = true
reth-chain-state.workspace = true
reth-db-api.workspace = true
reth-ethereum-engine-primitives.workspace = true
reth-ethereum-primitives.workspace = true
reth-primitives-traits = { workspace = true, features = ["secp256k1", "rayon"] }
reth-node-builder.workspace = true
reth-node-api.workspace = true
reth-node-ethereum.workspace = true
reth-network.workspace = true
reth-provider.workspace = true
reth-evm.workspace = true
reth-evm-ethereum.workspace = true
reth-execution-errors.workspace = true
reth-fs-util.workspace = true
reth-rpc-api.workspace = true
reth-rpc.workspace = true
reth-rpc-convert.workspace = true
reth-engine-primitives = { workspace = true, features = ["std"] }
reth-engine-local.workspace = true
reth-ethereum-consensus.workspace = true
reth-payload-primitives.workspace = true
reth-payload-validator.workspace = true
reth-payload-builder.workspace = true
reth-revm = { workspace = true, features = ["std"] }
reth-storage-errors.workspace = true
reth-node-core.workspace = true
reth-rpc-engine-api.workspace = true
reth-rpc-eth-api.workspace = true
reth-rpc-eth-types.workspace = true
reth-rpc-server-types.workspace = true
reth-rpc-builder.workspace = true
reth-stages.workspace = true
reth-stages-types.workspace = true

# telos
reth-telos-rpc.workspace = true
reth-telos-rpc-engine-api.workspace = true

# alloy
alloy-network.workspace = true
alloy-rpc-types-eth.workspace = true
alloy-rpc-types-engine.workspace = true
alloy-consensus.workspace = true
alloy-primitives.workspace = true
alloy-eips.workspace = true
alloy-evm.workspace = true
alloy-rlp.workspace = true

# async
tokio = { workspace = true, features = ["sync"] }

# revm
revm = { workspace = true, features = ["secp256k1", "blst", "c-kzg", "memory_limit", "optional_no_base_fee"] }

# cli
reth-cli.workspace = true
reth-ethereum-cli.workspace = true

# misc
clap = { workspace = true, features = ["derive", "env"] }
serde_json.workspace = true
serde = { workspace = true, features = ["derive"] }
jsonrpsee.workspace = true
eyre.workspace = true
thiserror.workspace = true
once_cell = { workspace = true, features = ["std"] }
alloy-genesis.workspace = true
sha2 = { workspace = true, features = ["std"] }

[dev-dependencies]
reth-db = { workspace = true, features = ["mdbx"] }
reth-consensus.workspace = true
tempfile.workspace = true
